program:
  seed: 42
  gen_rand_seed: True
  gpu: False

data:
  data_set_id: 3  # 1: CIFAR 10, 2: CIFAR 100, 3: MNIST
  test_ratio: 0.2
  val_ratio: 0.2

model:
  model_id: 4
  number_channels: 1
  out_channels: 32 
  number_classes: 10

training:
  batch_size: 128
  epochs: 10
  learning_rate: 1e-4
  epsilon: 1e-8
  grad_epsilon: 1e-3
  clip_factor: 0.1
